### ISSUE TITLE
No Action Triggered on Linux (WS 2020.3.1)

### ISSUE THREAD

**Issue by nidomiro** [iguissouma/nx-console-idea-plugin#10]
I currently have the problem that I cannot use the plugin on my Linux (Kubuntu 20.04) machine.
The plugin appears correctly, lists all apps/libs correctly but I cannot execute an action (eg. double-click on lint => nothing happens).
On mac the plugin works fine.

The only difference I found so far is that the mac has nx installed globally and my linux-machine does not.
My Linux-config looks like this:
![grafik](https://user-images.githubusercontent.com/15079172/103405392-377b5680-4b57-11eb-940d-f24affbd11b2.png)

Is there anything I'm missing?

**Comment by iguissouma** [comment]
Hello,

Maybe on the run configuration I'm using only the Nx Cli installed globally and in your case it's empty.  
<img width="793" alt="Screenshot 2020-12-31 at 18 10 00" src="https://user-images.githubusercontent.com/9085108/103419505-a4144680-4b93-11eb-81e7-7039ca4456e3.png">

I will investigate and fix that ASAP, we should be able to use the locally installed.
The run configuration should be marked as invalid when no Cli is found.

Thanks for reporting this issue.

**Comment by nidomiro** [comment]
Thanks :)

In my case I do not get to the point where a Run/Debug Config is created.
The "Nx Generate (Ui)" works flawless at the same time.

I may have the causing exception for you:
```
2021-01-01 12:29:01,140 [ 184534]   WARN - .ExternalResourceManagerExImpl - Cannot find standard resource. filename:/standardSchemas/jspxml.dtd class=class com.intellij.jsp.impl.JspResourcesProvider, classLoader:null 
2021-01-01 12:29:01,763 [ 185157]   INFO -         #NxSchematicsLoader.kt - Error while loading schematics info.
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at Object.join (path.js:1039:7)
    at Object.readAndCacheJsonFile (/.../Nx Console Idea/nxCli/utils.js:138:31)
    at /.../Nx Console Idea/nxCli/read-schematic-collection.js:106:53
    at Array.forEach (<anonymous>)
    at readCollectionSchematics (/.../Nx Console Idea/nxCli/read-schematic-collection.js:103:51)
    at readCollection (/.../Nx Console Idea/nxCli/read-schematic-collection.js:90:16)
    at /.../Nx Console Idea/nxCli/read-schematic-collection.js:62:61
    at Array.map (<anonymous>)
    at readSchematicCollectionsFromNodeModules (/.../Nx Console Idea/nxCli/read-schematic-co... 
2021-01-01 12:29:06,442 [ 189836]   INFO - rationStore.ComponentStoreImpl - Saving Project(name=Tasks, containerState=COMPONENT_CREATED, componentStore=/home/niclas/workspace/nidomiro.de/Tasks)RunManager took 19 ms 
2021-01-01 12:30:18,989 [ 262383]   WARN - .ExternalResourceManagerExImpl - Cannot find standard resource. filename:/standardSchemas/jspxml.dtd class=class com.intellij.jsp.impl.JspResourcesProvider, classLoader:null 
2021-01-01 12:30:28,072 [ 271466]   INFO - j.ide.actions.RevealFileAction - Timed out 
2021-01-01 12:30:28,073 [ 271467]   INFO - j.ide.actions.RevealFileAction - inotify_add_watch(/tmp/systemd-private-fd3027ea114947af8ebe72d4f4888232-colord.service-Yksyyi) failed: (Permission denied)
inotify_add_watch(/tmp/systemd-private-fd3027ea114947af8ebe72d4f4888232-haveged.service-iDuuQg) failed: (Permission denied)
inotify_add_watch(/tmp/systemd-private-fd3027ea114947af8ebe72d4f4888232-ModemManager.service-aqDSlf) failed: (Permission denied)
inotify_add_watch(/tmp/systemd-private-fd3027ea114947af8ebe72d4f4888232-systemd-logind.service-M5zGtg) failed: (Permission denied)
inotify_add_watch(/tmp/systemd-private-fd3027ea114947af8ebe72d4f4888232-systemd-resolved.service-EyxKOh) failed: (Permission denied)
inotify_add_watch(/tmp/systemd-private-fd3027ea114947af8ebe72d4f4888232-systemd-timesyncd.service-yXEEjj) failed: (Permission denied)
inotify_add_watch(/tmp/systemd-private-fd3027ea114947af8ebe72d4f4888232-upower.service-yfUTVf) failed: (Permission denied)
Hspell: can't open /usr/share/hspell/hebrew.wgz.sizes.
sonnet.plugins.hspell: HSpellDict::HSpellDict: Init failed
QWidget::insertAction: Attempt to insert null action
QWidget::insertAction: Attempt to insert null action
 
2021-01-01 12:30:37,479 [ 280873]   INFO - r.local.NodeJsLocalInterpreter - /usr/bin/node /usr/lib/node_modules/npm/bin/npm-cli.js config get prefix=/usr (203 ms) 
```

**Comment by iguissouma** [comment]
Please test using this new version, it should fix the problem.
Plugins>Install plugin from disk> choose the zip file.
[Nx Console Idea-0.14.0.zip](https://github.com/iguissouma/nx-console-idea-plugin/files/5758970/Nx.Console.Idea-0.14.0.zip)

**Comment by nidomiro** [comment]
Yes, it's working now, thanks :)
