### ISSUE TITLE
Cannot process toolwindow Nx Dep Graph (crash)

### ISSUE THREAD

**Issue by Hypenate** [iguissouma/nx-console-idea-plugin#107]
**Describe the bug:**
Cannot process toolwindow Nx Dep Graph

java.lang.RuntimeException: com.intellij.util.io.PersistentEnumeratorBase$CorruptedException: PersistentEnumerator storage corrupted C:\Users\benbe\AppData\Local\JetBrains\WebStorm2022.2\caches\names.dat
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:132)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSConnection.handleError(PersistentFSConnection.java:311)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.handleError(FSRecords.java:812)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.readAndHandleErrors(FSRecords.java:298)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.getNameId(FSRecords.java:592)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.findExistingChildInfo(PersistentFSImpl.java:465)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.lambda$findChildInfo$4(PersistentFSImpl.java:416)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.update(FSRecords.java:349)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.findChildInfo(PersistentFSImpl.java:453)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findInPersistence(VirtualDirectoryImpl.java:150)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.doFindChild(VirtualDirectoryImpl.java:132)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:78)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:538)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:45)
	at com.intellij.openapi.vfs.newvfs.VfsImplUtil.findFileByPath(VfsImplUtil.java:63)
	at com.intellij.openapi.vfs.impl.local.LocalFileSystemBase.findFileByPath(LocalFileSystemBase.java:123)
	at com.intellij.openapi.vfs.LocalFileSystem.findFileByNioFile(LocalFileSystem.java:46)
	at com.intellij.openapi.project.impl.ProjectExImpl.getBaseDir(ProjectExImpl.kt:134)
	at com.github.iguissouma.nxconsole.depGraph.NxDepGraphToolWindow.isApplicable(NxDepGraphToolWindow.kt:71)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.beanToTask(ToolWindowSetInitializer.kt:249)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.access$beanToTask(ToolWindowSetInitializer.kt:1)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt$computeToolWindowBeans$1.accept(ToolWindowSetInitializer.kt:279)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt$computeToolWindowBeans$1.accept(ToolWindowSetInitializer.kt)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:301)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.computeToolWindowBeans(ToolWindowSetInitializer.kt:275)
	at com.intellij.toolWindow.ToolWindowSetInitializer$1.get(ToolWindowSetInitializer.kt:100)
	at com.intellij.toolWindow.ToolWindowSetInitializer$1.get(ToolWindowSetInitializer.kt:82)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool.externalHelpQuiescePool(ForkJoinPool.java:2104)
	at java.base/java.util.concurrent.ForkJoinPool.awaitQuiescence(ForkJoinPool.java:3321)
	at com.intellij.idea.StartupUtil.start(StartupUtil.java:272)
	at com.intellij.idea.Main.bootstrap(Main.java:119)
	at com.intellij.idea.Main.main(Main.java:81)
Caused by: com.intellij.util.io.PersistentEnumeratorBase$CorruptedException: PersistentEnumerator storage corrupted C:\Users\benbe\AppData\Local\JetBrains\WebStorm2022.2\caches\names.dat
	at com.intellij.util.io.PersistentEnumeratorBase.catchCorruption(PersistentEnumeratorBase.java:618)
	at com.intellij.util.io.PersistentEnumeratorBase.doEnumerate(PersistentEnumeratorBase.java:272)
	at com.intellij.util.io.PersistentEnumeratorBase.enumerate(PersistentEnumeratorBase.java:285)
	at com.intellij.util.io.PersistentEnumerator.enumerate(PersistentEnumerator.java:125)
	at com.intellij.util.io.PersistentStringEnumerator.enumerate(PersistentStringEnumerator.java:70)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.lambda$getNameId$25(FSRecords.java:592)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.readAndHandleErrors(FSRecords.java:287)
	... 31 more

**Steps to reproduce:**
Open Webstorm

**Expected behavior:**
No errors

**Additional context:**
Using the latest versions of everything.
Webstorm 2022.2.2 (Build #WS-222.4167.31, built on September 14, 2022)
Nx Console Idea: 0.48.2

**Comment by iguissouma** [comment]
Hello,

It seems the IDE build-cache was corrupted.
Can you please try to in validate caches and restart the IDE?
