### ISSUE TITLE
Assertion failed error in WebStorm  2022.3.2

### ISSUE THREAD

**Issue by mvaljento** [iguissouma/nx-console-idea-plugin#144]
WebStorm gives the following error report when launching:

java.lang.Throwable: Assertion failed
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:254)
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:263)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.doFindChildById(VirtualDirectoryImpl.java:539)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords$1ParentFinder.findChild(FSRecords.java:598)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords$1ParentFinder.findDescendantByIdPath(FSRecords.java:591)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.findFileById(FSRecords.java:616)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.findFileById(PersistentFSImpl.java:1423)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.findFileById(PersistentFSImpl.java:58)
	at com.intellij.util.indexing.FileBasedIndexScanUtil.processFilesContainingAnyKey(FileBasedIndexScanUtil.java:248)
	at com.intellij.util.indexing.FileBasedIndexImpl.processFilesContainingAnyKey(FileBasedIndexImpl.java:1146)
	at com.intellij.psi.search.FilenameIndex.getVirtualFilesByNames(FilenameIndex.java:225)
	at com.intellij.psi.search.FilenameIndex.getVirtualFilesByName(FilenameIndex.java:62)
	at com.github.iguissouma.nxconsole.cli.config.NxConfigFromGlobs.<init>(NxConfig.kt:71)
	at com.github.iguissouma.nxconsole.cli.config.NxConfigProvider$Companion.getNxConfig$lambda$3$lambda$2(NxConfigProvider.kt:54)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:231)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:41)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:231)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:232)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.github.iguissouma.nxconsole.cli.config.NxConfigProvider$Companion.getNxConfig(NxConfigProvider.kt:47)
	at com.github.iguissouma.nxconsole.buildTools.NxJsonUtil.doBuildStructure(NxJsonUtil.kt:71)
	at com.github.iguissouma.nxconsole.buildTools.NxJsonUtil.listTasks$lambda$0(NxJsonUtil.kt:48)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:872)
	at com.github.iguissouma.nxconsole.buildTools.NxJsonUtil.listTasks(NxJsonUtil.kt:46)
	at com.github.iguissouma.nxconsole.buildTools.NxService.hasScripts(NxService.kt:114)
	at com.github.iguissouma.nxconsole.buildTools.NxService.access$hasScripts(NxService.kt:39)
	at com.github.iguissouma.nxconsole.buildTools.NxService$detectAllBuildfilesInContentRoots$1.invoke(NxService.kt:105)
	at com.github.iguissouma.nxconsole.buildTools.NxService$detectAllBuildfilesInContentRoots$1.invoke(NxService.kt:102)
	at com.github.iguissouma.nxconsole.buildTools.NxService.detectAllBuildfilesInContentRoots$lambda$1(NxService.kt:102)
	at com.intellij.lang.javascript.buildTools.base.JsbtUtil.iterateOverContentRoots(JsbtUtil.java:76)
	at com.github.iguissouma.nxconsole.buildTools.NxService.detectAllBuildfilesInContentRoots(NxService.kt:102)
	at com.github.iguissouma.nxconsole.buildTools.NxJsbtStartupActivity$Companion.doDetect$lambda$6(NxJsbtStartupActivity.kt:62)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:872)
	at com.github.iguissouma.nxconsole.buildTools.NxJsbtStartupActivity$Companion.doDetect(NxJsbtStartupActivity.kt:58)
	at com.github.iguissouma.nxconsole.buildTools.NxJsbtStartupActivity$Companion.scheduleDetection$lambda$4$lambda$3$lambda$2(NxJsbtStartupActivity.kt:42)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:246)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833) 

**Steps to reproduce:**

Installed NX Console Idea 0.55.0 in WebStorm 2022.3.2 on Mac Ventura 13.2.1 (22D68).

**Comment by hopefullToo** [comment]
I have the same problem in IntelliJ IDEA.
Version of Nx Console IDEA: 0.56.0

Version/runcontext IDEA: 
IntelliJ IDEA 2022.3.2 (Ultimate Edition)
Build #IU-223.8617.56, built on January 26, 2023

Runtime version: 17.0.5+1-b653.25 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.2.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON

Regards 
Bernd
