### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by broslukasz** [iguissouma/nx-console-idea-plugin#148]
**Describe the bug:**
When I click "install" to this plugin it fails

**Steps to reproduce:**
I go to settings -> plugins -> search nx in marketplace tab -> choose proper "Nx Console Idea" plugin -> I get: "Plugin 'Nx Console Idea' download or installation failed"

**Expected behavior:**
It should successfully install

**Additional context:**
I also try doing it via web page (https://plugins.jetbrains.com/plugin/15101-nx-console-idea) and it also fails with "Plugin error", "Plugins failed to load"

WebStorm 2022.2.4
Build #WS-222.4459.24, built on November 22, 2022
Licensed to Xebia sp. z o.o. / Łukasz Bros
Subscription is active until March 27, 2023.
Runtime version: 17.0.5+7-b469.71 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2008M
Cores: 8
Non-Bundled Plugins:
com.github.etkachev.nxwebstorm (0.13.0)

**Comment by iguissouma** [comment]
Can you install other plugins without issues?

I can install it without issues, I thought it maybe a clash between nx-webstorm plugin and Nx Console Ides, but I install both with success.

What logs says?
Show log in explorer, open idea.log and see if there's some errors related to installation.

**Comment by broslukasz** [comment]
2023-03-13 08:24:30,724 [ 276802]   WARN - #c.i.i.p.PluginInstallOperation - C:\Users\lbros\AppData\Local\Temp\plugin17190166574541022674\Nx Console Idea\lib\nx-console-idea-plugin-0.56.0.jar
java.nio.file.AccessDeniedException: C:\Users\lbros\AppData\Local\Temp\plugin17190166574541022674\Nx Console Idea\lib\nx-console-idea-plugin-0.56.0.jar
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:275)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
	at java.base/java.nio.file.Files.deleteIfExists(Files.java:1191)
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor235.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.intellij.openapi.util.io.FileUtilRt$NIOReflect$1.performDelete(FileUtilRt.java:178)
	at com.intellij.openapi.util.io.FileUtilRt$NIOReflect$1.invoke(FileUtilRt.java:157)
	at jdk.proxy2/jdk.proxy2.$Proxy38.visitFile(Unknown Source)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2811)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2882)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.intellij.openapi.util.io.FileUtilRt$NIOReflect.deleteRecursively(FileUtilRt.java:101)
	at com.intellij.openapi.util.io.FileUtilRt.deleteRecursivelyNIO(FileUtilRt.java:925)
	at com.intellij.openapi.util.io.NioFiles.deleteRecursively(NioFiles.java:137)
	at com.intellij.ide.plugins.PluginDescriptorLoader.loadDescriptorFromArtifact(PluginDescriptorLoader.kt:567)
	at com.intellij.openapi.updateSettings.impl.PluginDownloader.loadDescriptorFromArtifact(PluginDownloader.java:268)
	at com.intellij.openapi.updateSettings.impl.PluginDownloader.prepareToInstall(PluginDownloader.java:234)
	at com.intellij.ide.plugins.PluginInstallOperation.prepareToInstall(PluginInstallOperation.java:258)
	at com.intellij.ide.plugins.PluginInstallOperation.prepareToInstallWithCallback(PluginInstallOperation.java:226)
	at com.intellij.ide.plugins.PluginInstallOperation.prepareToInstall(PluginInstallOperation.java:198)
	at com.intellij.ide.plugins.PluginInstallOperation.run(PluginInstallOperation.java:138)
	at com.intellij.ide.plugins.newui.MyPluginModel.runInstallOperation(MyPluginModel.java:441)
	at com.intellij.ide.plugins.newui.MyPluginModel$1.run(MyPluginModel.java:409)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by iguissouma** [comment]
I don't this it's related to the plugin but rather the IDE and environment windows.
Try to delete this directory and install again `C:\Users\lbros\AppData\Local\Temp\plugin17190166574541022674\Nx Console Idea`

**Comment by broslukasz** [comment]
I put plugin manuali into a proper folder and it works

**Comment by broslukasz** [comment]
I used this instruction:
https://intellij-support.jetbrains.com/hc/en-us/community/posts/4409329934482--SOLVED-getting-java-nio-file-AccessDeniedException-when-installing-IdeaVIM-to-Pycharm-on-Windows-10
