### ISSUE TITLE
Nx generate not available for React projects

### ISSUE THREAD

**Issue by Gieted** [iguissouma/nx-console-idea-plugin#18]
![obraz](https://user-images.githubusercontent.com/35242233/111483637-45dc1600-8735-11eb-81b4-f304cf3cb51e.png)

The button is blank and can't be pressed.

### Steps to reproduce:
1. Clear IDE's cache
2. Create new nx workspace
3. Select React template in nx cli dialog
4. Select default options for rest prompts
5. Try to use nx generate

I've found log entry that might be linked to the issue:

```
2021-03-17 15:15:49,534 [  18375]   INFO -         #NxSchematicsLoader.kt - Error while loading schematics info.
internal/.../modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '@angular-devkit/core'
Require stack:
- C:/.../Nx Console Idea/nxCli/utils.js
- C:/.../Nx Console Idea/nxCli/read-schematic-collection.js
- C:/.../Nx Console Idea/nxCli/schematicsInfoProvider.js
- C:/.../Nx Console Idea/nxCli/runner.js
    at Function.Module._resolveFilename (internal/.../modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/.../modules/cjs/loader.js:725:27)
    at Module.require (internal/.../modules/cjs/loader.js:952:19)
    at require (internal/.../modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:/.../Nx Console Idea/nxCli/utils.js:3:16)
    at Module._compile (internal/.../modules/cjs/loader.js:1063:30)
    at ... 
```

For Angular projects Nx generate works as it should.

OS: Windows 10
Idea version: 2020.3.3
Plugin version: 0.23.0

**Comment by iguissouma** [comment]
Hello,
You are right, the plugin use some angular dependencies that are not present on a react project.
I will try to fix this issue.

As a temporary workaround you can try to install the @angular/cli on your project as devDependencies and restart the IDE(to evict cached schematics...).

`npm i --save-dev @angular/cli`

Thanks for reporting this.
