### ISSUE TITLE
Double shift on webstorm to global search freeze IDE first time

### ISSUE THREAD

**Issue by yoan-asdrubal** [iguissouma/nx-console-idea-plugin#43]
**What steps will reproduce the issue?**
 Every first time I Open webstorm project, double tab on shit for global search, the IDE get freezed for some seconds, after that its works great always. I reported that issue to webstorm teams (https://youtrack.jetbrains.com/issue/WEB-53857) and they suggest me to disabled nx-console-ui pluggin after check webstorm log. I tried and its works. its seems that problem is related to the plugin

**What is the expected result?**

Webstorm do not freeze firs time double tab on shift to global search.

**Comment by iguissouma** [comment]
Yes you are right.
In some places it will freeze the first time(double shift, new menu....)  to load the schematics in the project synchronously.
Then it will be cached and not freeze for the next time.
It's something I will look how to make it async.

**Comment by bennycode** [comment]
@yoan-asdrubal you may want to rename "shit" to "shift". 😅

**Comment by Thomas-Schindler** [comment]
Hi @all,

I'm using the Plugin version 0.36.0 with Intellij IDEA 2021.3.1 and made also the Observation, that the IDE freezes for a short time, when selecting "File -> New" in the menu bar, the first time.  And the following Exception is logged:

```
java.lang.Throwable: Synchronous execution on EDT: "C:\Program Files\nodejs\node.exe" "C:\Users\tschindler\AppData\Roaming\JetBrains\IntelliJIdea2021.3\plugins\Nx Console Idea\nxCli\runner.js" C:/Users/tschindler/workspace/empic-nx/angular.json ./schematicsInfoProvider.js, see com.intellij.execution.process.OSProcessHandler#checkEdtAndReadAction() Javadoc for resolutions
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.execution.process.OSProcessHandler.checkEdtAndReadAction(OSProcessHandler.java:173)
	at com.intellij.execution.process.OSProcessHandler.waitFor(OSProcessHandler.java:104)
	at com.intellij.execution.process.CapturingProcessRunner.runProcess(CapturingProcessRunner.java:39)
	at com.intellij.execution.process.CapturingProcessHandler.runProcess(CapturingProcessHandler.java:43)
	at com.github.iguissouma.nxconsole.schematics.NxSchematicsLoaderKt.grabCommandOutput(NxSchematicsLoader.kt:63)
	at com.github.iguissouma.nxconsole.schematics.NxSchematicsLoaderKt.loadSchematicsInfoJson(NxSchematicsLoader.kt:55)
	at com.github.iguissouma.nxconsole.schematics.NxSchematicsLoaderKt.doLoad(NxSchematicsLoader.kt:32)
	at com.github.iguissouma.nxconsole.schematics.NxCliSchematicsRegistryServiceImpl.getSchematics$lambda-3$lambda-2(NxCliSchematicsRegistryServiceImpl.kt:51)
	at com.github.iguissouma.nxconsole.schematics.NxCliSchematicsRegistryServiceImpl$CachedSchematics.getUpToDateOrCompute(NxCliSchematicsRegistryServiceImpl.kt:100)
	at com.github.iguissouma.nxconsole.schematics.NxCliSchematicsRegistryServiceImpl.getSchematics(NxCliSchematicsRegistryServiceImpl.kt:49)
	at com.github.iguissouma.nxconsole.schematics.NxCliSchematicsRegistryService$DefaultImpls.getSchematics(NxCliSchematicsRegistryService.kt:27)
	at com.github.iguissouma.nxconsole.schematics.NxCliSchematicsRegistryServiceImpl.getSchematics(NxCliSchematicsRegistryServiceImpl.kt:23)
	at com.github.iguissouma.nxconsole.actions.NxNewGenerateActionGroup.getChildren(NxNewGenerateActionGroup.kt:19)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doGetChildren(ActionUpdater.java:612)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$1(ActionUpdater.java:110)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$callAction$8(ActionUpdater.java:191)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$callAction$9(ActionUpdater.java:189)
	at com.intellij.openapi.actionSystem.impl.ActionUpdateEdtExecutor.lambda$computeOnEdt$0(ActionUpdateEdtExecutor.java:45)
	at com.intellij.openapi.actionSystem.impl.Utils.lambda$expandActionGroupFastTrack$3(Utils.java:256)
	at com.intellij.openapi.actionSystem.impl.Utils.runLoopAndWaitForFuture(Utils.java:582)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroupFastTrack(Utils.java:254)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroupImpl(Utils.java:171)
	at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:278)
	at com.intellij.openapi.actionSystem.impl.ActionMenu.fillMenuInner(ActionMenu.java:362)
	at com.intellij.openapi.actionSystem.impl.Utils.performWithRetries(Utils.java:620)
	at com.intellij.openapi.actionSystem.impl.ActionMenu.fillMenu(ActionMenu.java:341)
	at com.intellij.openapi.actionSystem.impl.ActionMenu.setPopupMenuVisible(ActionMenu.java:312)
	at java.desktop/javax.swing.JPopupMenu.menuSelectionChanged(JPopupMenu.java:1484)
	at java.desktop/javax.swing.MenuSelectionManager.setSelectedPath(MenuSelectionManager.java:129)
	at java.desktop/javax.swing.plaf.basic.BasicMenuUI.appendPath(BasicMenuUI.java:258)
	at java.desktop/javax.swing.plaf.basic.BasicMenuUI$Actions.actionPerformed(BasicMenuUI.java:316)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:317)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:249)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:498)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

Maybe this is related to this issue and it may help in chasing the Problem.

By the way: Thank you for this great plugin!

**Comment by iguissouma** [comment]
The load generators was reworked should be better as we are not using node process to load schematics.
