### ISSUE TITLE
Errors with Webstorm 2020.3

### ISSUE THREAD

**Issue by nidomiro** [iguissouma/nx-console-idea-plugin#5]
First I really like the plugin and it saves me a lot of time :)

After updating to WebStorm 2020.3 I observed Exceptions keep happening:
```
Unable to serialize NxVcsManagerConfiguration state

com.intellij.util.xmlb.XmlSerializationException: Can't serialize instance of class com.github.iguissouma.nxconsole.vcs.NxVcsConfiguration
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:143)
	at com.intellij.util.ReflectionUtil.createAsDataClass(ReflectionUtil.java:521)
	at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:451)
	at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:426)
	at com.intellij.util.xmlb.SkipDefaultValuesSerializationFilters.getDefaultValue(SkipDefaultValuesSerializationFilters.java:53)
	at com.intellij.util.xmlb.SkipDefaultValuesSerializationFilters.getDefaultBean(SkipDefaultValuesSerializationFilters.java:46)
	at com.intellij.util.xmlb.SkipDefaultsSerializationFilter.equal(SkipDefaultsSerializationFilter.java:32)
	at com.intellij.util.xmlb.BeanBinding.serializePropertyInto(BeanBinding.java:108)
	at com.intellij.util.xmlb.BeanBinding.serializeInto(BeanBinding.java:93)
	at com.intellij.serialization.xml.KotlinAwareBeanBinding.serializeInto(KotlinAwareBeanBinding.kt:39)
	at com.intellij.util.xmlb.BeanBinding.serialize(BeanBinding.java:84)
	at com.intellij.configurationStore.JdomSerializerImpl.serialize(xmlSerializer.kt:48)
	at com.intellij.configurationStore.XmlSerializer.serialize(xmlSerializer.kt:19)
	at com.intellij.configurationStore.XmlSerializer.serialize$default(xmlSerializer.kt:18)
	at com.intellij.configurationStore.SaveSessionBaseKt.serializeState(SaveSessionBase.kt:46)
	at com.intellij.configurationStore.SaveSessionBase.setState(SaveSessionBase.kt:20)
	at com.intellij.configurationStore.ComponentStoreImpl.setStateToSaveSessionProducer(ComponentStoreImpl.kt:342)
	at com.intellij.configurationScript.providers.MyProjectStore.setStateToSaveSessionProducer(ConfigurationScriptProjectStoreFactory.kt:69)
	at com.intellij.configurationStore.ComponentStoreImpl.commitComponent(ComponentStoreImpl.kt:335)
	at com.intellij.configurationStore.ComponentStoreImpl.commitComponents$intellij_platform_configurationStore_impl(ComponentStoreImpl.kt:233)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.commitComponents$intellij_platform_configurationStore_impl(ComponentStoreWithExtraComponents.kt:96)
	at com.intellij.configurationStore.ComponentStoreImpl$commitComponentsOnEdt$$inlined$withEdtContext$intellij_platform_configurationStore_impl$1.invokeSuspend(ComponentStoreImpl.kt:709)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at com.intellij.openapi.application.constraints.BaseConstrainedExecution$Companion$scheduleWithinConstraints$1.invoke(BaseConstrainedExecution.kt:68)
	at com.intellij.openapi.application.constraints.BaseConstrainedExecution$Companion.scheduleWithinConstraints(BaseConstrainedExecution.kt:71)
	at com.intellij.openapi.application.constraints.BaseConstrainedExecution.scheduleWithinConstraints(BaseConstrainedExecution.kt:38)
	at com.intellij.openapi.application.impl.BaseExpirableExecutorMixinImpl.access$scheduleWithinConstraints$s1153900543(BaseExpirableExecutorMixinImpl.kt:12)
	at com.intellij.openapi.application.impl.BaseExpirableExecutorMixinImpl$scheduleWithinConstraints$$inlined$Runnable$1.run(Runnable.kt:19)
	at com.intellij.openapi.application.impl.AppUIExecutorImpl$MyEdtExecutor.execute(AppUIExecutorImpl.kt:70)
	at com.intellij.openapi.application.impl.BaseExpirableExecutorMixinImpl.scheduleWithinConstraints(BaseExpirableExecutorMixinImpl.kt:23)
	at com.intellij.openapi.application.constraints.ConstrainedCoroutineDispatcherImpl.dispatch(ConstrainedCoroutineDispatcher.kt:34)
	at kotlinx.coroutines.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:288)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:166)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.configurationStore.ComponentStoreImpl.commitComponentsOnEdt$intellij_platform_configurationStore_impl(ComponentStoreImpl.kt:720)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.saveSettingsSavingComponentsAndCommitComponents$intellij_platform_configurationStore_impl(ComponentStoreWithExtraComponents.kt:87)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents$saveSettingsSavingComponentsAndCommitComponents$1.invokeSuspend(ComponentStoreWithExtraComponents.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.intellij.configurationStore.StoreUtil$Companion.saveDocumentsAndProjectsAndApp(storeUtil.kt:74)
	at com.intellij.ide.plugins.DynamicPlugins.unloadPlugin(DynamicPlugins.kt:471)
	at com.intellij.openapi.updateSettings.impl.PluginDownloader.tryInstallWithoutRestart(PluginDownloader.java:280)
	at com.intellij.openapi.updateSettings.impl.UpdateInstaller.installDownloadedPluginUpdates(UpdateInstaller.kt:112)
	at com.intellij.openapi.updateSettings.impl.PluginUpdateDialog$5.lambda$run$0(PluginUpdateDialog.java:210)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:324)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.util.ReflectionUtil.createAsDataClass(ReflectionUtil.java:497)
	... 79 more
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method com.github.iguissouma.nxconsole.vcs.NxVcsConfiguration.<init>, parameter project
	at com.github.iguissouma.nxconsole.vcs.NxVcsConfiguration.<init>(NxVcsConfiguration.kt)
	... 84 more
```

```
Failed to load schematics info.
internal/.../modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '@angular-devkit/core'
Require stack:
- /.../Nx Console Idea/nxCli/runner.js
    at Function.Module._resolveFilename (internal/.../modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/.../modules/cjs/loader.js:747:27)
    at Module.require (internal/.../modules/cjs/loader.js:974:19)
    at require (internal/.../modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/.../Nx Console Idea/nxCli/utils.js:3:16)
    at Module._compile (internal/.../modules/cjs/loader.js:1085:30)
    at Object.Module._extensions..js (internal/.../modules/cjs/loader.js:1114:10)
    at Module.load (internal/.../modules/cjs/loader.js:950:32)
    at Function.Module....

java.lang.Throwable
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:77)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:169)
	at com.github.iguissouma.nxconsole.schematics.NxSchematicsLoaderKt.grabCommandOutput(NxSchematicsLoader.kt:96)
	at com.github.iguissouma.nxconsole.schematics.NxSchematicsLoaderKt.loadSchematicsInfoJson(NxSchematicsLoader.kt:58)
	at com.github.iguissouma.nxconsole.schematics.NxSchematicsLoaderKt.doLoad(NxSchematicsLoader.kt:35)
	at com.github.iguissouma.nxconsole.schematics.NxCliSchematicsRegistryServiceImpl$getSchematics$$inlined$let$lambda$2.get(NxCliSchematicsRegistryServiceImpl.kt:51)
	at com.github.iguissouma.nxconsole.schematics.NxCliSchematicsRegistryServiceImpl$getSchematics$$inlined$let$lambda$2.get(NxCliSchematicsRegistryServiceImpl.kt:23)
	at com.github.iguissouma.nxconsole.schematics.NxCliSchematicsRegistryServiceImpl$CachedSchematics.getUpToDateOrCompute(NxCliSchematicsRegistryServiceImpl.kt:96)
	at com.github.iguissouma.nxconsole.schematics.NxCliSchematicsRegistryServiceImpl.getSchematics(NxCliSchematicsRegistryServiceImpl.kt:49)
	at com.github.iguissouma.nxconsole.schematics.NxCliSchematicsRegistryService$DefaultImpls.getSchematics(NxCliSchematicsRegistryService.kt:27)
	at com.github.iguissouma.nxconsole.schematics.NxCliSchematicsRegistryServiceImpl.getSchematics(NxCliSchematicsRegistryServiceImpl.kt:23)
	at com.github.iguissouma.nxconsole.execution.NxGenerateRunAnythingProvider$getSchematics$1$1.run(NxGenerateRunAnythingProvider.kt:155)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:324)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

```
Error while loading schematics info.
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:122:11)
    at Object.join (path.js:1039:7)
    at Object.readAndCacheJsonFile (/.../Nx Console Idea/nxCli/utils.js:138:31)
    at /.../Nx Console Idea/nxCli/read-schematic-collection.js:106:53
    at Array.forEach (<anonymous>)
    at readCollectionSchematics (/.../Nx Console Idea/nxCli/read-schematic-collection.js:103:51)
    at readCollection (/.../Nx Console Idea/nxCli/read-schematic-collection.js:90:16)
    at /.../Nx Console Idea/nxCli/read-schematic-collection.js:62:61
    at Array.map (<anonymous>)
    at readSchematicCollectionsFromNodeModules (/.../Nx Console Idea/nxCli/read-schematic-co...

java.lang.Throwable
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:77)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:169)
	at com.github.iguissouma.nxconsole.schematics.NxSchematicsLoaderKt.grabCommandOutput(NxSchematicsLoader.kt:82)
	at com.github.iguissouma.nxconsole.schematics.NxSchematicsLoaderKt.loadSchematicsInfoJson(NxSchematicsLoader.kt:58)
	at com.github.iguissouma.nxconsole.schematics.NxSchematicsLoaderKt.doLoad(NxSchematicsLoader.kt:35)
	at com.github.iguissouma.nxconsole.schematics.NxCliSchematicsRegistryServiceImpl$getSchematics$$inlined$let$lambda$2.get(NxCliSchematicsRegistryServiceImpl.kt:51)
	at com.github.iguissouma.nxconsole.schematics.NxCliSchematicsRegistryServiceImpl$getSchematics$$inlined$let$lambda$2.get(NxCliSchematicsRegistryServiceImpl.kt:23)
	at com.github.iguissouma.nxconsole.schematics.NxCliSchematicsRegistryServiceImpl$CachedSchematics.getUpToDateOrCompute(NxCliSchematicsRegistryServiceImpl.kt:96)
	at com.github.iguissouma.nxconsole.schematics.NxCliSchematicsRegistryServiceImpl.getSchematics(NxCliSchematicsRegistryServiceImpl.kt:49)
	at com.github.iguissouma.nxconsole.schematics.NxCliSchematicsRegistryService$DefaultImpls.getSchematics(NxCliSchematicsRegistryService.kt:27)
	at com.github.iguissouma.nxconsole.schematics.NxCliSchematicsRegistryServiceImpl.getSchematics(NxCliSchematicsRegistryServiceImpl.kt:23)
	at com.github.iguissouma.nxconsole.actions.NxNewGenerateActionGroup$getChildren$1.run(NxNewGenerateActionGroup.kt:29)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:270)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by iguissouma** [comment]
Thank you for your feedback.

I've seen these problems. I will try to investigate and fix them.

Can you please confirm that the schematics are loaded for you like below?

<img width="1047" alt="Screenshot 2020-12-03 at 11 40 36" src="https://user-images.githubusercontent.com/9085108/100999240-cc8d2e80-355c-11eb-8b9b-29b40e556780.png">

**Comment by nidomiro** [comment]
Yes, I can see them

**Comment by iguissouma** [comment]
The bugs are not blocking but I will get rid of them.
