### ISSUE TITLE
Error on start in webstorm

### ISSUE THREAD

**Issue by NorthwooDzp** [iguissouma/nx-console-idea-plugin#75]
when open project in webstorm error occurs (wsl)
```
java.lang.Throwable: AWT events are prohibited inside NxNewGenerateActionGroup#getChildren (com.github.iguissouma.nxconsole.actions.NxNewGenerateActionGroup); got java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=javax.swing.Timer$DoPostEvent@5becef80,notifier=null,catchExceptions=false,when=1653214176183] on sun.awt.windows.WToolkit@287acb67
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.ide.ProhibitAWTEvents.dispatch(ProhibitAWTEvents.java:40)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:460)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:943)
	at com.intellij.openapi.progress.util.ProgressWindow.lambda$startBlocking$4(ProgressWindow.java:205)
	at com.intellij.openapi.application.impl.ApplicationImpl.runUnlockingIntendedWrite(ApplicationImpl.java:899)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:201)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$execFromEDT$6(ProgressRunner.java:321)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731)
	at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108)
	at com.intellij.openapi.progress.impl.ProgressRunner.execFromEDT(ProgressRunner.java:318)
	at com.intellij.openapi.progress.impl.ProgressRunner.submit(ProgressRunner.java:259)
	at com.intellij.openapi.progress.impl.ProgressRunner.submitAndGet(ProgressRunner.java:185)
	at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:477)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:385)
	at com.intellij.openapi.progress.ProgressManager.run(ProgressManager.java:191)
	at com.intellij.execution.wsl.WslDistributionDescriptor.executeOrRunTask(WslDistributionDescriptor.java:198)
	at com.intellij.execution.wsl.WslDistributionDescriptor.lambda$new$1(WslDistributionDescriptor.java:50)
	at com.intellij.execution.wsl.WslDistributionDescriptor$2.compute(WslDistributionDescriptor.java:212)
	at com.intellij.openapi.util.ClearableLazyValue.getValue(ClearableLazyValue.java:39)
	at com.intellij.execution.wsl.WslDistributionDescriptor$2.getValue(WslDistributionDescriptor.java:222)
	at com.intellij.execution.wsl.WslDistributionDescriptor.getMntRoot(WslDistributionDescriptor.java:128)
	at com.intellij.execution.wsl.WSLDistribution.getMntRoot(WSLDistribution.java:527)
	at com.intellij.execution.wsl.WSLDistribution.getWslPath(WSLDistribution.java:518)
	at com.intellij.javascript.nodejs.interpreter.wsl.WslCommandLineConfigurator.convertPathToWsl(WslCommandLineConfigurator.java:81)
	at com.intellij.javascript.nodejs.interpreter.wsl.WslCommandLineConfigurator.configure(WslCommandLineConfigurator.java:54)
	at com.github.iguissouma.nxconsole.schematics.NxSchematicsLoaderKt.loadSchematicsInfoJson(NxSchematicsLoader.kt:54)
	at com.github.iguissouma.nxconsole.schematics.NxSchematicsLoaderKt.doLoad(NxSchematicsLoader.kt:32)
	at com.github.iguissouma.nxconsole.schematics.NxCliSchematicsRegistryServiceImpl.getSchematics$lambda-3$lambda-2(NxCliSchematicsRegistryServiceImpl.kt:51)
	at com.github.iguissouma.nxconsole.schematics.NxCliSchematicsRegistryServiceImpl$CachedSchematics.getUpToDateOrCompute(NxCliSchematicsRegistryServiceImpl.kt:100)
	at com.github.iguissouma.nxconsole.schematics.NxCliSchematicsRegistryServiceImpl.getSchematics(NxCliSchematicsRegistryServiceImpl.kt:49)
	at com.github.iguissouma.nxconsole.schematics.NxCliSchematicsRegistryService.getSchematics(NxCliSchematicsRegistryService.kt:27)
	at com.github.iguissouma.nxconsole.actions.NxNewGenerateActionGroup.getChildren(NxNewGenerateActionGroup.kt:19)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doGetChildren(ActionUpdater.java:663)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$1(ActionUpdater.java:113)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$6(ActionUpdater.java:210)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:58)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:58)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$7(ActionUpdater.java:208)
	at com.intellij.openapi.actionSystem.impl.ActionUpdateEdtExecutor.lambda$computeOnEdt$0(ActionUpdateEdtExecutor.java:45)
	at com.intellij.openapi.actionSystem.impl.Utils.lambda$expandActionGroupFastTrack$5(Utils.java:270)
	at com.intellij.openapi.actionSystem.impl.Utils.runLoopAndWaitForFuture(Utils.java:595)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroupFastTrack(Utils.java:268)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroupImpl(Utils.java:180)
	at com.intellij.openapi.actionSystem.impl.Utils.lambda$fillMenu$6(Utils.java:294)
	at com.intellij.openapi.actionSystem.impl.Utils.computeWithRetries(Utils.java:633)
	at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:293)
	at com.intellij.openapi.actionSystem.impl.ActionMenu.fillMenu(ActionMenu.java:411)
	at com.intellij.openapi.actionSystem.impl.ActionMenu.setPopupMenuVisible(ActionMenu.java:360)
	at java.desktop/javax.swing.JPopupMenu.menuSelectionChanged(JPopupMenu.java:1484)
	at java.desktop/javax.swing.MenuSelectionManager.setSelectedPath(MenuSelectionManager.java:129)
	at java.desktop/javax.swing.plaf.basic.BasicMenuUI.appendPath(BasicMenuUI.java:258)
	at java.desktop/javax.swing.plaf.basic.BasicMenuUI$Actions.actionPerformed(BasicMenuUI.java:316)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:317)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:249)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by iguissouma** [comment]
Hello,
I'm in process to rewrite this part of code where I'm not invoking node to load generators.
Can you test this new approach with wsl?
 
[Nx Console Idea-0.43.0.zip](https://github.com/iguissouma/nx-console-idea-plugin/files/8749228/Nx.Console.Idea-0.43.0.zip)

**Comment by NorthwooDzp** [comment]
Another error on start

**Comment by iguissouma** [comment]
Please see if error disappear with this version.
It's a work in progress, trying to initialise generators with defaults value from nx.json...

[Nx Console Idea-0.43.1.zip](https://github.com/iguissouma/nx-console-idea-plugin/files/8757475/Nx.Console.Idea-0.43.1.zip)

**Comment by NorthwooDzp** [comment]
Error disappear, but panel with nx tasks also. BTW item in context menu "Remove nx app or lib" does not do anything

**Comment by iguissouma** [comment]
I have no idea for the delay maybe scanning the project take a while...
We should have same delay for previous version 0.42.0

For the delete App or lib Maybe related to this issue #74, Do you have the "root" property in your project.json files?
