### ISSUE TITLE
Failing to use NX generation with the plugin

### ISSUE THREAD

**Issue by vitalybe** [iguissouma/nx-console-idea-plugin#88]
**Describe the bug:**
Trying to using the generator menu bar in our project. The menu action becomes disabled and I am getting the following stack trace from WebStorm:

```
getChildren failed for ActionGroup(com.github.iguissouma.nxconsole.actions.NxNewGenerateActionGroup, id=Nx.NxNewGenerateActionGroup) with text=Nx Generate (Ui)...

java.lang.NullPointerException: null cannot be cast to non-null type kotlin.String
	at com.github.iguissouma.nxconsole.readers.GetGeneratorsKt$readWorkspaceGeneratorsCollection$2.invoke(getGenerators.kt:319)
	at com.github.iguissouma.nxconsole.readers.GetGeneratorsKt$readWorkspaceGeneratorsCollection$2.invoke(getGenerators.kt:316)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:786)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:816)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:807)
	at com.github.iguissouma.nxconsole.readers.GetGeneratorsKt.readWorkspaceGeneratorsCollection(getGenerators.kt:339)
	at com.github.iguissouma.nxconsole.readers.GetGeneratorsKt.checkAndReadWorkspaceGenerators(getGenerators.kt:281)
	at com.github.iguissouma.nxconsole.readers.GetGeneratorsKt.getGenerators(getGenerators.kt:29)
	at com.github.iguissouma.nxconsole.schematics.NxSchematicsLoaderKt.doLoadGenerators(NxSchematicsLoader.kt:9)
	at com.github.iguissouma.nxconsole.schematics.NxCliSchematicsRegistryServiceImpl.getSchematics$lambda-3$lambda-2(NxCliSchematicsRegistryServiceImpl.kt:50)
	at com.github.iguissouma.nxconsole.schematics.NxCliSchematicsRegistryServiceImpl$CachedSchematics.getUpToDateOrCompute(NxCliSchematicsRegistryServiceImpl.kt:94)
	at com.github.iguissouma.nxconsole.schematics.NxCliSchematicsRegistryServiceImpl.getSchematics(NxCliSchematicsRegistryServiceImpl.kt:48)
	at com.github.iguissouma.nxconsole.schematics.NxCliSchematicsRegistryService.getSchematics(NxCliSchematicsRegistryService.kt:27)
	at com.github.iguissouma.nxconsole.actions.NxNewGenerateActionGroup.getChildren(NxNewGenerateActionGroup.kt:47)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doGetChildren(ActionUpdater.java:663)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$1(ActionUpdater.java:113)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$6(ActionUpdater.java:210)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:58)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:58)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$7(ActionUpdater.java:208)
	at com.intellij.openapi.actionSystem.impl.ActionUpdateEdtExecutor.lambda$computeOnEdt$0(ActionUpdateEdtExecutor.java:45)
	at com.intellij.openapi.actionSystem.impl.Utils.lambda$expandActionGroupFastTrack$5(Utils.java:270)
	at com.intellij.openapi.actionSystem.impl.Utils.runLoopAndWaitForFuture(Utils.java:595)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroupFastTrack(Utils.java:268)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroupImpl(Utils.java:180)
	at com.intellij.openapi.actionSystem.impl.Utils.lambda$fillMenu$6(Utils.java:294)
	at com.intellij.openapi.actionSystem.impl.Utils.computeWithRetries(Utils.java:633)
	at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:293)
	at com.intellij.openapi.actionSystem.impl.ActionMenu.fillMenu(ActionMenu.java:411)
	at com.intellij.openapi.actionSystem.impl.ActionMenu.setPopupMenuVisible(ActionMenu.java:360)
	at java.desktop/javax.swing.JPopupMenu.menuSelectionChanged(JPopupMenu.java:1484)
	at java.desktop/javax.swing.MenuSelectionManager.setSelectedPath(MenuSelectionManager.java:129)
	at java.desktop/javax.swing.plaf.basic.BasicMenuUI.appendPath(BasicMenuUI.java:258)
	at java.desktop/javax.swing.plaf.basic.BasicMenuUI$Actions.actionPerformed(BasicMenuUI.java:316)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:317)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:249)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by iguissouma** [comment]
Hello,

Seems that you have a `schema.json` without `$id `or `id` on the file.
So I can't calculate the name of collection maybe I will fallback to `unknown`

[Nx Console Idea-0.46.3.zip](https://github.com/iguissouma/nx-console-idea-plugin/files/9022223/Nx.Console.Idea-0.46.3.zip)
 
can you try this version? and tell me if any schematic appear with unknown name.

**Comment by vitalybe** [comment]
That solved it, thanks!
