### ISSUE TITLE
In Webstorm/Idea Ultimate 2022.2 I get a crash

### ISSUE THREAD

**Issue by bulldog98** [iguissouma/nx-console-idea-plugin#98]
I cannot open the generate right click action.

The stacktrace:
```
NxNewGenerateActionGroup#getChildren@ProjectViewPopup (com.github.iguissouma.nxconsole.actions.NxNewGenerateActionGroup), actionId=Nx.NxNewGenerateActionGroup, text='Nx Generate (Ui)...'

java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class java.util.Map (java.util.ArrayList and java.util.Map are in module java.base of loader 'bootstrap')
	at com.github.iguissouma.nxconsole.readers.GetGeneratorsKt.schemaToOptions(getGenerators.kt:186)
	at com.github.iguissouma.nxconsole.readers.GetGeneratorsKt.normalizeSchema(getGenerators.kt:87)
	at com.github.iguissouma.nxconsole.readers.GetGeneratorsKt.normalizeSchema$default(getGenerators.kt:81)
	at com.github.iguissouma.nxconsole.readers.GetGeneratorsKt$readWorkspaceGeneratorsCollection$2.invoke(getGenerators.kt:355)
	at com.github.iguissouma.nxconsole.readers.GetGeneratorsKt$readWorkspaceGeneratorsCollection$2.invoke(getGenerators.kt:337)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:787)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:817)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:808)
	at com.github.iguissouma.nxconsole.readers.GetGeneratorsKt.readWorkspaceGeneratorsCollection(getGenerators.kt:360)
	at com.github.iguissouma.nxconsole.readers.GetGeneratorsKt.checkAndReadWorkspaceGenerators(getGenerators.kt:302)
	at com.github.iguissouma.nxconsole.readers.GetGeneratorsKt.getGenerators(getGenerators.kt:33)
	at com.github.iguissouma.nxconsole.schematics.NxSchematicsLoaderKt.doLoadGenerators(NxSchematicsLoader.kt:12)
	at com.github.iguissouma.nxconsole.schematics.NxCliSchematicsRegistryServiceImpl.getSchematics$lambda-3$lambda-2(NxCliSchematicsRegistryServiceImpl.kt:50)
	at com.github.iguissouma.nxconsole.schematics.NxCliSchematicsRegistryServiceImpl$CachedSchematics.getUpToDateOrCompute(NxCliSchematicsRegistryServiceImpl.kt:94)
	at com.github.iguissouma.nxconsole.schematics.NxCliSchematicsRegistryServiceImpl.getSchematics(NxCliSchematicsRegistryServiceImpl.kt:48)
	at com.github.iguissouma.nxconsole.schematics.NxCliSchematicsRegistryService.getSchematics(NxCliSchematicsRegistryService.kt:27)
	at com.github.iguissouma.nxconsole.actions.NxNewGenerateActionGroup.getChildren(NxNewGenerateActionGroup.kt:47)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doGetChildren(ActionUpdater.java:670)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$1(ActionUpdater.java:117)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$6(ActionUpdater.java:211)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:66)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$7(ActionUpdater.java:207)
	at com.intellij.openapi.actionSystem.impl.ActionUpdateEdtExecutor.lambda$computeOnEdt$0(ActionUpdateEdtExecutor.java:45)
	at com.intellij.openapi.actionSystem.impl.Utils.lambda$expandActionGroupFastTrack$5(Utils.java:290)
	at com.intellij.openapi.actionSystem.impl.Utils.runLoopAndWaitForFuture(Utils.java:743)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroupFastTrack(Utils.java:288)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroupImpl(Utils.java:207)
	at com.intellij.openapi.actionSystem.impl.Utils.lambda$fillMenu$6(Utils.java:314)
	at com.intellij.openapi.actionSystem.impl.Utils.computeWithRetries(Utils.java:773)
	at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:313)
	at com.intellij.openapi.actionSystem.impl.ActionMenu.fillMenu(ActionMenu.java:439)
	at com.intellij.openapi.actionSystem.impl.ActionMenu.setPopupMenuVisible(ActionMenu.java:384)
	at java.desktop/javax.swing.JPopupMenu.menuSelectionChanged(JPopupMenu.java:1509)
	at java.desktop/javax.swing.MenuSelectionManager.setSelectedPath(MenuSelectionManager.java:134)
	at java.desktop/javax.swing.plaf.basic.BasicMenuUI.appendPath(BasicMenuUI.java:264)
	at java.desktop/javax.swing.plaf.basic.BasicMenuUI$Actions.actionPerformed(BasicMenuUI.java:322)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:311)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:243)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
	```

**Comment by bulldog98** [comment]
Thank for fixing it
